# Generated by Django 5.1.2 on 2024-11-13 18:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bagage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bagage', models.CharField(choices=[('Valise', 'Valise'), ('Sac', 'Sac'), ('Carton', 'Carton')], default='Valise', max_length=64)),
                ('taille', models.CharField(choices=[('P', 'Petite'), ('M', 'Moyenne'), ('G', 'Grande')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('duration', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.CharField(choices=[('Passenger', 'Passenger'), ('Driver', 'Driver')], max_length=10)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(default='', max_length=15)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.abonnement')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_matricule', models.CharField(blank=True, default='', max_length=16)),
                ('car_marque', models.CharField(blank=True, default='', max_length=64)),
                ('car_modele', models.CharField(blank=True, default='', max_length=64)),
                ('car_age', models.IntegerField(blank=True, null=True)),
                ('car_nombre_place', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coupon'),
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=64)),
                ('destination', models.CharField(default='', max_length=64)),
                ('price_per_seat', models.FloatField()),
                ('passengers_sex', models.CharField(default='', max_length=16)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('is_full', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
                ('driver', models.ForeignKey(limit_choices_to={'type': 'Driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=64)),
                ('destination', models.CharField(default='', max_length=64)),
                ('driver_sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('price_min', models.FloatField()),
                ('price_max', models.FloatField()),
                ('date', models.DateField()),
                ('heure_min', models.TimeField()),
                ('heure_max', models.TimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('list_bagage', models.ManyToManyField(blank=True, to='home.bagage')),
                ('passenger', models.ForeignKey(limit_choices_to={'type': 'Passenger'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_list', models.ManyToManyField(blank=True, to='home.trip')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trajet')),
            ],
        ),
    ]
