# Generated by Django 5.1.2 on 2024-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trajet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='car',
        ),
        migrations.AddField(
            model_name='trajet',
            name='places',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
