# Generated by Django 5.1.2 on 2024-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_trajet_car_trajet_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='bagage',
            field=models.CharField(default='Leger', max_length=16),
        ),
    ]
