# Generated by Django 5.1.2 on 2024-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_trajet_bagage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bagage',
            field=models.CharField(default='Leger', max_length=16),
        ),
    ]
