# Generated by Django 5.1.2 on 2024-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_bagage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='list_bagage',
        ),
        migrations.AddField(
            model_name='trip',
            name='bagage',
            field=models.CharField(default='Leger', max_length=16),
        ),
    ]
