# Generated by Django 5.1.2 on 2024-11-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_trip_list_bagage_trip_bagage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='price_min',
        ),
    ]
