# Generated by Django 5.1.2 on 2024-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_trip_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='confirmed_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
